# codemagic.yaml
# CI/CD workflow for Codemagic
# Secret variables should be in a group named 'firebase_secrets'

workflows:
  android-app-distribution:
    name: Android App Distribution
    environment:
      flutter: 3.35.4
      vars:
        BUILD_TOOL: "shorebird"
      groups:
        - firebase_secrets
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: DEBUG - List Environment Variables
        script: |
          echo "--- Listing available environment variables ---"
          printenv | sort
          echo "-------------------------------------------"

      - name: Install Shorebird CLI
        script: |
          echo "Installing Shorebird CLI..."
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          # Persist PATH for next steps
          echo 'export PATH="$HOME/.shorebird/bin:$PATH"' >> $CM_ENV_PATH
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird --version || echo "⚠️ Shorebird installation not found"

      - name: Set up Firebase Key File
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
          # Persist Google Cloud credentials for tools like FlutterFire
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV
          # Persist variable for Gradle task
          echo "FIREBASE_SERVICE_ACCOUNT_KEY_PATH=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV

      - name: Authenticate with Google Cloud
        script: |
          gcloud auth activate-service-account --key-file=$CM_BUILD_DIR/firebase_service_account_key.json

      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get

      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli

      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android

      - name: Conditional Build (APK)
        script: |
          if [ "$BUILD_TOOL" = "shorebird" ]; then
            echo "Building with Shorebird..."
            shorebird build apk --release
          else
            echo "Building with Flutter..."
            flutter build apk --release
          fi

      - name: Distribute to Firebase App Distribution
        script: |
          echo "Uploading to Firebase App Distribution..."
          cd android
          ./gradlew appDistributionUploadRelease

    artifacts:
      - build/app/outputs/apk/release/*.apk

  android-patch-distribution:
    name: Android Patch Distribution
    environment:
      flutter: 3.35.4
      groups:
        - firebase_secrets
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'patch-android-*'
          include: true
    scripts:
      - name: Install Shorebird CLI
        script: |
          echo "Installing Shorebird CLI..."
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          echo 'export PATH="$HOME/.shorebird/bin:$PATH"' >> $CM_ENV_PATH
          export PATH="$HOME/.shorebird/bin:$PATH"

      - name: Set up Firebase Key File
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV

      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get

      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli

      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android

      - name: Release Shorebird Patch
        script: |
          echo "Releasing patch to Shorebird..."
          shorebird patch apk --release
