# codemagic.yaml
# This file defines the CI/CD workflow for Codemagic.
# Your secret variables should be in a group named 'firebase_secrets' in the Codemagic UI.

workflows:
  android-app-distribution:
    name: Android App Distribution
    environment:
      flutter: 3.35.4
      vars:
        BUILD_TOOL: "shorebird"
      groups:
        - firebase_secrets
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install Shorebird CLI
        script: |
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
      - name: Set up key file
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
          echo "FIREBASE_SERVICE_ACCOUNT_KEY_PATH=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV
      - name: Authenticate with Google Cloud
        script: |
          gcloud auth activate-service-account --key-file=$CM_BUILD_DIR/firebase_service_account_key.json
      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get
      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli
      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android
      - name: Conditional Build (APK)
        script: |
          if [ "$BUILD_TOOL" = "shorebird" ]; then
            echo "Building with Shorebird..."
            shorebird build apk --release
          else
            echo "Building with Flutter..."
            flutter build apk --release
          fi
      - name: Distribute to Firebase App Distribution
        script: |
          echo "Uploading to Firebase App Distribution..."
          cd android
          ./gradlew appDistributionUploadRelease
    artifacts:
      - build/app/outputs/apk/release/*.apk

  android-patch-distribution:
    name: Android Patch Distribution
    environment:
      flutter: 3.35.4
      groups:
        - firebase_secrets
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'patch-android-*'
          include: true
    scripts:
      - name: Install Shorebird CLI
        script: |
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
      - name: Set up key file
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
      - name: Authenticate with Google Cloud
        script: |
          gcloud auth activate-service-account --key-file=$CM_BUILD_DIR/firebase_service_account_key.json
      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get
      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli
      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android
      - name: Release Shorebird Patch
        script: |
          echo "Releasing patch to Shorebird..."
          shorebird patch apk --release
