# codemagic.yaml
# CI/CD workflow for Codemagic (Flutter + Shorebird + Firebase + GitHub Releases)
# Secret variables should be in groups: 'firebase_secrets' and 'github'

workflows:
  android-app-distribution:
    name: Android App Distribution
    environment:
      flutter: 3.35.4
      vars:
        BUILD_TOOL: "shorebird"
      groups:
        - firebase_secrets
        - github
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'release-android-v*'
          include: true

    scripts:
      - name: Set up Firebase Key File
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV
          echo "FIREBASE_SERVICE_ACCOUNT_KEY_PATH=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV

      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get

      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli

      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android

      - name: Run Flutter Tests
        script: |
          set -e
          flutter test --coverage

      - name: Install Shorebird & Build APK
        script: |
          set -e
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          export PATH="$HOME/.shorebird/bin:$PATH"
          
          if [ "$BUILD_TOOL" = "shorebird" ]; then
            echo "Building with Shorebird..."
            shorebird release android --artifact apk
          else
            echo "Building with Flutter..."
            flutter build apk --release
          fi

      - name: Distribute to Firebase App Distribution
        script: |
          echo "Uploading to Firebase App Distribution..."
          cd android
          ./gradlew appDistributionUploadRelease

      - name: Create GitHub Release
        script: |
          set -e
          export GH_TOKEN=$GITHUB_TOKEN

          APP_NAME="Todo"
          VERSION=$(echo "$CM_TAG" | sed 's/release-android-v//')

          echo "Creating GitHub release for $APP_NAME v$VERSION..."
          gh release create "$CM_TAG" \
            --title "$APP_NAME v$VERSION (Android)" \
            --notes "📦 **Automated release for $APP_NAME v$VERSION**  
            
            ✅ Built with Shorebird  
            🚀 Distributed via Firebase App Distribution  
            🔒 Signed and ready for release." \
            build/app/outputs/apk/release/app-release.apk

    artifacts:
      - build/app/outputs/apk/release/*.apk


  android-patch-distribution:
    name: Android Patch Distribution
    environment:
      flutter: 3.35.4
      groups:
        - firebase_secrets
        - github
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'patch-android-*'
          include: true

    scripts:
      - name: Set up Firebase Key File
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV

      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get

      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli

      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android

      - name: Run Flutter Tests
        script: |
          set -e
          flutter test --coverage

      - name: Install Shorebird & Patch
        script: |
          set -e
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          export PATH="$HOME/.shorebird/bin:$PATH"
          echo "Releasing patch to Shorebird..."
          shorebird patch android

      - name: Create GitHub Release for Patch
        script: |
          set -e
          export GH_TOKEN=$GITHUB_TOKEN

          APP_NAME="Todo"
          VERSION=$(echo "$CM_TAG" | sed 's/patch-android-//')

          echo "Creating GitHub patch release for $APP_NAME $VERSION..."
          gh release create "$CM_TAG" \
            --title "$APP_NAME v$VERSION (Patch)" \
            --notes "🔧 **Automated patch release for $APP_NAME v$VERSION**  
            
            🛠 Bug fixes and performance improvements  
            🚀 Delivered via Shorebird patch system."
