# codemagic.yaml
# CI/CD workflow for Codemagic integrating Shorebird and Firebase App Distribution.
# Ensure that your Firebase-related secrets are stored under the group name 'firebase_secrets' in Codemagic.

workflows:
  android-app-distribution:
    name: Android App Distribution
    environment:
      flutter: 3.35.4
      vars:
        BUILD_TOOL: "shorebird" # change to "flutter" if you want to disable shorebird build
      groups:
        - firebase_secrets
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install Shorebird CLI
        script: |
          echo "Installing Shorebird CLI..."
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird --version || echo "⚠️ Shorebird not detected"
          echo "PATH=$PATH" >> $CM_ENV
          ls -la $HOME/.shorebird/bin || echo "⚠️ Shorebird directory missing"

      - name: Set up Firebase Service Account Key
        script: |
          echo "Setting up Firebase key file..."
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV
          echo "FIREBASE_SERVICE_ACCOUNT_KEY_PATH=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV

      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get

      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli

      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android

      - name: Conditional Build (APK)
        script: |
          echo "Starting conditional build..."
          if [ "$BUILD_TOOL" = "shorebird" ]; then
            echo "Building with Shorebird..."
            shorebird build apk --release
          else
            echo "Building with Flutter..."
            flutter build apk --release
          fi

      - name: Distribute to Firebase App Distribution
        script: |
          echo "Uploading to Firebase App Distribution..."
          cd android
          ./gradlew appDistributionUploadRelease

    artifacts:
      - build/app/outputs/apk/release/*.apk

  android-patch-distribution:
    name: Android Patch Distribution
    environment:
      flutter: 3.35.4
      groups:
        - firebase_secrets
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'patch-android-*'
          include: true
    scripts:
      - name: Install Shorebird CLI
        script: |
          echo "Installing Shorebird CLI..."
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird --version || echo "⚠️ Shorebird not detected"
          echo "PATH=$PATH" >> $CM_ENV
          ls -la $HOME/.shorebird/bin || echo "⚠️ Shorebird directory missing"

      - name: Set up Firebase Service Account Key
        script: |
          echo "Setting up Firebase key file..."
          echo $FIREBASE_SERVICE_ACCOUNT_KEY | base64 --decode > $CM_BUILD_DIR/firebase_service_account_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/firebase_service_account_key.json" >> $CM_ENV

      - name: Set up Flutter
        script: |
          flutter doctor
          flutter pub get

      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli

      - name: Generate Firebase options
        script: |
          flutterfire configure --project=$FIREBASE_PROJECT_ID --yes --platforms=android

      - name: Release Shorebird Patch
        script: |
          echo "Releasing patch to Shorebird..."
          shorebird patch apk --release
