import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:todo_app/src/features/ai_task/domain/ai_task_draft.dart';
import 'package:todo_app/src/features/ai_task/domain/ai_task_response.dart';
import 'package:todo_app/src/features/ai_task/presentation/cubit/ai_task_state.dart';
import 'package:todo_app/src/features/todo_list/domain/todo_model.dart';
import 'package:todo_app/src/features/ai_task/application/gemini_service.dart';
import 'package:todo_app/src/features/todo_list/presentation/cubits/todo_cubit.dart';

class AiTaskCubit extends Cubit<AiTaskState> {
  final GeminiService _geminiService;
  final TodoCubit _todoCubit;

  AiTaskCubit(this._geminiService, this._todoCubit) : super(const AiTaskInitial());

  Future<void> processUserMessage(String message) async {
    emit(const AiTaskLoading());
    try {
      final AiTaskResponse response = await _geminiService.askGemini(message);

      if (response.status == AiTaskResponseStatus.clarificationNeeded) {
        emit(AiTaskClarificationNeeded(response.clarificationQuestion!));
      } else if (response.status == AiTaskResponseStatus.taskReady) {
        emit(AiTaskReadyForConfirmation(response.taskDraft!));
      } else if (response.status == AiTaskResponseStatus.error) {
        emit(AiTaskError(response.errorMessage!));
      }
    } catch (e) {
      emit(AiTaskError(e.toString()));
    }
  }

  Future<void> confirmTask(AiTaskDraft draft) async {
    emit(const AiTaskLoading());
    try {
      final Todo todo = Todo(
        id: -1, // Will be generated by the database
        name: draft.title,
        description: draft.description,
        deadline: draft.deadline,
        isCompleted: false,
      );
      await _todoCubit.addTodo(todo);
      emit(const AiTaskSaved());
    } catch (e) {
      emit(AiTaskError(e.toString()));
    }
  }

  void resetState() {
    emit(const AiTaskInitial());
  }
}
